language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '10'
  - '11'
  - '12'
after_success:
  - yarn run semantic-release
scripts:
  - yarn test
  - yarn run build
branches:
  only: master
